// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import keystatic from '@keystatic/astro';
import vercel from '@astrojs/vercel';

// https://astro.build/config
export default defineConfig({
	adapter: vercel(),
	integrations: [
		starlight({
			title: 'One Degree North — Lessons',
			description: 'Subteam training modules for FRC Team 4817, One Degree North.',
			customCss: ['./src/styles/lessons.css'],
			sidebar: [
				// Autogenerated from folders in src/content/docs/lessons/.
				// Adding a new subteam = adding a new folder there, no config change needed.
				{ label: 'Lessons', items: [{ autogenerate: { directory: 'lessons' } }] },
				{ label: '← Back to team site', link: '/' },
			],
		}),
		react(),
		keystatic(),
	],
});
