// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import keystatic from '@keystatic/astro';
import sitemap from '@astrojs/sitemap';
import netlify from '@astrojs/netlify';

// https://astro.build/config
export default defineConfig({
	// TODO: replace with the real Netlify subdomain after the first deploy,
	// then redeploy so canonical URLs, the sitemap, and social previews resolve.
	site: 'https://frc-website.netlify.app',
	adapter: netlify(),
	integrations: [
		starlight({
			title: 'One Degree North — Lessons',
			description: 'Subteam training modules for FRC Team 4817, One Degree North.',
			favicon: '/favicon.svg',
			customCss: ['./src/styles/lessons.css'],
			sidebar: [
				// Autogenerated from folders in src/content/docs/lessons/.
				// Adding a new subteam = adding a new folder there, no config change needed.
				{ label: 'Lessons', items: [{ autogenerate: { directory: 'lessons' } }] },
				{ label: '← Back to team site', link: '/' },
			],
		}),
		react(),
		keystatic(),
		sitemap(),
	],
});
