// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import keystatic from '@keystatic/astro';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';

// https://astro.build/config
export default defineConfig({
	// The live Vercel URL. If a custom domain is added later, update this
	// (and public/robots.txt) to match, then redeploy.
	site: 'https://frc-website-zeta.vercel.app',
	adapter: vercel(),
	integrations: [
		starlight({
			// One Starlight instance serves both /lessons/ and /documentation/,
			// so the title stays section-neutral.
			title: 'One Degree North',
			description:
				'Subteam training modules and reference documentation for FRC Team 4817, One Degree North.',
			favicon: '/favicon.svg',
			customCss: ['./src/styles/starlight.css'],
			head: [
				{
					// Default the lessons to dark for first-time visitors
					// (Starlight otherwise follows the OS setting). Users can
					// still switch via Starlight's theme picker.
					tag: 'script',
					content:
						"try{if(!localStorage.getItem('starlight-theme'))localStorage.setItem('starlight-theme','dark')}catch(e){}",
				},
			],
			sidebar: [
				// Both groups are autogenerated from folders in
				// src/content/docs/. Adding a new subteam = adding a new folder
				// under lessons/ (or documentation/), no config change needed.
				{
					label: 'Lessons',
					items: [{ autogenerate: { directory: 'lessons', collapsed: true } }],
				},
				{
					label: 'Documentation',
					items: [
						{ autogenerate: { directory: 'documentation', collapsed: true } },
					],
				},
				{ label: '← Back to team site', link: '/' },
			],
		}),
		react(),
		keystatic(),
		sitemap(),
	],
});
